

export const allBlogData = [
  {
    id: 1,
    slug: "building-a-profitable-and-sustainable-business-model",
    batchName: "Business",
    image: "/images/home01/blog/blog1.png",
    itmeText: "Harry Jilson",
    dateText: "March 14, 2025",
    description: "Building a profitable and sustainable business model",
  },
  {
    id: 2,
    slug: "how-to-identify-your-target-audience-effectively",
    batchName: "Marketing",
    image: "/images/home01/blog/blog2.png",
    itmeText: "Sara Miller",
    dateText: "April 02, 2025",
    description: "How to identify your target audience effectively",
  },
  {
    id: 3,
    slug: "top-strategies-for-digital-growth-in-2025",
    batchName: "Strategy",
    image: "/images/home01/blog/blog3.png",
    itmeText: "John Carter",
    dateText: "April 18, 2025",
    description: "Top strategies for digital growth in 2025",
  },
  {
    id: 4,
    slug: "understanding-brand-identity-and-voice",
    batchName: "Branding",
    image: "/images/home01/blog/blog4.png",
    itmeText: "Emily Rose",
    dateText: "February 28, 2025",
    description: "Understanding brand identity and voice",
  },
  {
    id: 5,
    slug: "scaling-your-startup-with-limited-resources",
    batchName: "Startup",
    image: "/images/home01/blog/blog5.png",
    itmeText: "Mark Twain",
    dateText: "January 10, 2025",
    description: "Scaling your startup with limited resources",
  },
  {
    id: 6,
    slug: "the-power-of-content-marketing-for-b2b",
    batchName: "Content",
    image: "/images/home01/blog/blog6.png",
    itmeText: "Lisa Brown",
    dateText: "March 30, 2025",
    description: "The power of content marketing for B2B businesses",
  },
];